# NumPy Practice Questions

**Instructions:** Dear Students Each question is self‑explanatory. Read the markdown prompt and write the code in the cell below it where marked `# answer here`. Keep solutions simple and focused on the asked concept.

- Q1–Q30: Single-topic questions in sequence (basics → indexing → operations → aggregations → reshaping/broadcasting → utilities).

- Q31–Q35: Multi‑concept (combine 2–3 ideas you practiced).

- Q36–Q40: Use a single dataset loaded via **pandas** and perform **NumPy** operations on it. The file `students_scores.csv` is already available in the same folder as this notebook.


### Q1. Create a 1D NumPy array from the Python list `[1, 2, 3, 4, 5]` and print its type and contents.

In [77]:
# answer here
import numpy as np
import pandas as pd

arr1 = np.array([1,2,3,4,5])
print(arr1.astype)
print(arr1)

<built-in method astype of numpy.ndarray object at 0x000001EE0AEDD9B0>
[1 2 3 4 5]


### Q2. Create a 2D NumPy array from `[[1, 2, 3], [4, 5, 6]]` and print its `shape` and `ndim`.

In [78]:
# answer here
arr2 = np.array([[1,2,3], [4,5,6]])
print(arr2.shape)
print(arr2.ndim)
arr2

(2, 3)
2


array([[1, 2, 3],
       [4, 5, 6]])

### Q3. Create an array of 6 zeros and print it.

In [79]:
# answer here
arr3 = np.zeros(6)
arr3

array([0., 0., 0., 0., 0., 0.])

### Q4. Create an array of 5 ones (float) and print it.

In [80]:
# answer here
arr4 = np.ones(5)
arr4

array([1., 1., 1., 1., 1.])

### Q5. Use `np.arange` to create an array from 2 to 14 (inclusive of 2, exclusive of 14) with a step of 2 and print it.

In [81]:
# answer here
arr5 = np.arange(2,14,2)
arr5


array([ 2,  4,  6,  8, 10, 12])

### Q6. Use `np.linspace` to create 5 evenly spaced values from 0 to 1 and print them.

In [82]:
# answer here
arr6 = np.linspace(0,1,5)
arr6

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### Q7. Create an integer array `[10, 20, 30]` then convert it to `float` dtype and print both arrays.

In [83]:
# answer here
arr7_1 = np.array([10,20,30])
print(arr7_1, type(arr7_1))
arr7_2 = arr7_1.astype(float)
print(arr7_2, arr7_2.astype)

[10 20 30] <class 'numpy.ndarray'>
[10. 20. 30.] <built-in method astype of numpy.ndarray object at 0x000001EE0AEDD350>


### Q8. Create an array of 12 numbers from 0 to 11 and reshape it to `3x4`; print the reshaped array.

In [84]:
# answer here
arr8 = 12
ans8 = np.arange(arr8).reshape(3,4)
ans8


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Q9. For the array `a = np.array([[1,2,3],[4,5,6]])`, print `a.shape`, `a.ndim`, and `a.size`.

In [85]:
# answer here
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)
print(a.ndim)
print(a.size)

(2, 3)
2
6


### Q10. For the array `a = np.array([1,2,3], dtype=np.int32)`, print `a.dtype` and `a.itemsize`.

In [86]:
# answer here
a = np.array([1,2,3])
dtype = np.int32()
print('type: ',a.dtype,'|','size: ',a.itemsize)

type:  int64 | size:  8


### Q11. Given `arr = np.array([10, 20, 30, 40, 50])`, print the first element, last element, and the element at index 2.

In [87]:
# answer here
arr11 = np.array([10,20,30,40,50])
print(arr11[0])
print(arr11[-1])
print(arr11[2])

10
50
30


### Q12. Given `arr = np.array([5, 10, 15, 20, 25])`, use negative indexing to print the last two elements.

In [88]:
# answer here
arr12 = np.array([5,10,15,20,25])
print(arr12[-2:])

[20 25]


### Q13. Given `arr = np.array([0,1,2,3,4,5,6,7,8,9])`, print the slice from index 2 to 7 (exclusive).

In [89]:
# answer here
arr13 = np.array([0,1,2,3,4,5,6,7,8,9])
print(arr13[2:7])

[2 3 4 5 6]


### Q14. Given `m = np.arange(1,13).reshape(3,4)`, print the second row and the third column (as 1D slices).

In [90]:
# answer here
m = np.arange(1,13).reshape(3,4)
print(m[1:2, 2:3])
print(m)

[[7]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### Q15. Given `m = np.arange(1,13).reshape(3,4)`, print the submatrix containing rows 0 to 1 and columns 1 to 3.

In [91]:
# answer here
print(m[0:2,1:4])

[[2 3 4]
 [6 7 8]]


### Q16. Given `arr = np.arange(1,11)`, create a boolean mask for even numbers and print the even elements.

In [92]:
# answer here
arr16 = np.arange(1,11)
mask = arr16 % 2 == 0
print(arr16[mask])

[ 2  4  6  8 10]


### Q17. Given `arr = np.arange(1,11)`, set all odd elements to `-1` (modify in place) and print the result.

In [93]:
# answer here
arr17 = np.arange(1,11)
arr17[arr17 % 2 != 0] = -1
arr17

array([-1,  2, -1,  4, -1,  6, -1,  8, -1, 10])

### Q18. Given `arr = np.array([1,2,3])`, add `5` to every element and print the result (element‑wise).

In [94]:
# answer here
arr18 = np.array([1,2,3])
ans = arr18 + 5 
ans

array([6, 7, 8])

### Q19. Given `a = np.array([1,2,3])` and `b = np.array([4,5,6])`, print `a + b` and `a * b` (element‑wise).

In [95]:
# answer here
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a*b)

[5 7 9]
[ 4 10 18]


### Q20. Given `a = np.array([1,2,3])` and `b = np.array([[10],[20],[30]])`, use broadcasting to compute `a + b` and print it.

In [96]:
# answer here
a = np.array([1,2,3])
b = np.array([[10],[20],[30]])
print(a+b)


[[11 12 13]
 [21 22 23]
 [31 32 33]]


### Q21. Given `arr = np.array([3, 7, 2, 9, 5])`, print its `sum`, `mean`, `min`, and `max`.

In [97]:
# answer here
arr21 = np.array([3,7,2,9,5])
print(arr21.sum())
print(arr21.mean())
print(arr21.min())
print(arr21.max())

26
5.2
2
9


### Q22. Given `m = np.arange(1,13).reshape(3,4)`, print the sum along axis 0 and along axis 1.

In [98]:
# answer here
arr22 = np.arange(1,13).reshape(3,4)
print(arr22)
print(arr22.sum(axis = 0))
print(arr22.sum(axis = 1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[15 18 21 24]
[10 26 42]


### Q23. Given `arr = np.array([10, 20, 5, 40, 25])`, print the indices of the `max` and `min` elements using `np.argmax` and `np.argmin`.

In [99]:
# answer here
arr23 = np.array([10,20,5,40,25])
print(np.argmax(arr23))
print(np.argmin(arr23))

3
2


### Q24. Given `arr = np.array([3, 3, 1, 2, 2, 2, 5])`, print the sorted array and the unique values using `np.unique`.

In [100]:
# answer here
arr24 = np.array([3,3,1,2,2,2,5])
sort24 = np.sort(arr24)
print(np.unique(sort24))
for i in np.unique(sort24):
    print(i)

[1 2 3 5]
1
2
3
5


### Q25. Given `arr = np.array([9, 1, 5, 3, 7])`, sort it in ascending order and print the result (do not modify original).

In [101]:
# answer here
arr25 = np.array([9,1,5,3,7])
newsorted = np.sort(arr25)
print(newsorted)

[1 3 5 7 9]


### Q26. Given `a = np.array([1,2,3])` and `b = np.array([4,5,6])`, horizontally concatenate them and print the result.

In [102]:
# answer here
arr26_1 = np.array([1,2,3])
arr26_2 = np.array([4,5,6])
new = np.concat((arr26_1,arr26_2), axis = 0)
print(new)

[1 2 3 4 5 6]


### Q27. Given `A = np.array([[1,2],[3,4]])` and `B = np.array([[5,6],[7,8]])`, stack them vertically and print the result.

In [103]:
# answer here
arr27_1 = np.array([[1,2], [3,4]])
arr27_2 = np.array([[5,6], [7,8]])
new = np.concat((arr27_1,arr27_2), axis = 0)
print(new)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### Q28. Given `arr = np.arange(1,13)`, split it into 3 equal parts and print each part.

In [104]:
# answer here
arr28 = np.arange(1,13)
new = np.split(arr28,3)
print(new)
print()
for i in new:
    print(i)

[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]


### Q29. Set a random seed (e.g., 42), generate 5 random integers from 0 to 9 using `np.random.randint`, and print them.

In [105]:
# answer here
import random
np.random.seed(1) #it helps to maintain the random values 
arr29 = np.random.randint(0,10,5)
print(arr29)

[5 8 9 5 0]


### Q30. Given `arr = np.array([-3, 1, -1, 4, -2, 5])`, use `np.where` to replace negative values with `0` and print the new array.

In [106]:
# answer here
arr30 = np.array([-3,1,-1,4,-2,5])
new = np.where(arr30 <0 ,0, arr30) #replace the values 
print(new)


[0 1 0 4 0 5]


### Q31. Create a 3D array of shape `(2, 3, 4)` using `np.arange` then compute the mean along axis 2 and print the result.

In [107]:
# answer here
arr31 = np.arange(24).reshape(2,3,4)
print(arr31)
m = arr31.mean(axis = 2)
print(m)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[ 1.5  5.5  9.5]
 [13.5 17.5 21.5]]


### Q32. Create an array from `[5, 10, 15, 20, 25]`, slice out `[10, 15, 20]`, then normalize that slice to range 0–1 using min‑max formula and print it.

In [108]:
# answer here
arr32 = np.array([5,10,15,20,25])
s = arr32[1:4]
print(s)
normalized = (s - s.min()) / (s.max() - s.min()) # formula x - x(min) / x(max) - x(min)
print(normalized)

[10 15 20]
[0.  0.5 1. ]


### Q33. Create two 1D arrays `a=[1,2,3]` and `b=[4,5,6]`; compute the dot product and also form a `3x2` matrix from `a` and `b` and print both results.

In [109]:
# answer here
arr33_1 = np.array([1,2,3])
arr33_2 = np.array([4,5,6])
print(arr33_1*arr33_2)
new = np.dot(arr33_1,arr33_2)
print('dot product:',new)
new2 = np.column_stack((arr33_1,arr33_2))
print(new2)

[ 4 10 18]
dot product: 32
[[1 4]
 [2 5]
 [3 6]]


### Q34. Create an array of 12 values (1–12), reshape it to `3x4`, then count how many values are greater than `6` and print the count.

In [110]:
# answer here
arr34 = np.arange(1,13).reshape(3,4)
new = np.sum(arr34>6)
print(new)

6


### Q35. Create an array from 0–9; replace all odd numbers with `-1` *except* keep the first and last elements unchanged; print the final array.

In [111]:
# answer here
arr35 = np.arange(0,10)
new = np.where((arr35 % 2 != 0) & (arr35 != arr35[0]) & (arr35 != arr35[-1]), -1, arr35 )
print(new)

[ 0 -1  2 -1  4 -1  6 -1  8  9]


### Dataset for Q36–Q40

A CSV file **`students_scores.csv`** is already placed in this folder (Link-https://drive.google.com/file/d/1B7zDahhmQzXkQmvskS27H07B4Xftf9xA/view?usp=sharing).  

Columns: `id, math, english, science` (10 students). Use **pandas** to import the file and then perform **NumPy** operations.


### Q36. Import `students_scores.csv` as a pandas DataFrame `df`. Then convert the `math`, `english`, and `science` columns to separate NumPy arrays and print their shapes.

In [112]:
# answer here
df = pd.read_csv(r'C:\prerit\Hungry-Coders\numpy\students_scores.csv')
print(df)
math = df['math'].to_numpy()
english = df['english'].to_numpy()
science = df['science'].to_numpy()
print('math size:',math.shape)
print('english size:',english.shape)
print('science size:',science.shape)

    id  math  english  science
0  S01    78       65       72
1  S02    56       70       60
2  S03    88       81       90
3  S04    45       55       48
4  S05    92       76       85
5  S06    67       62       71
6  S07    73       80       66
7  S08    59       58       64
8  S09    84       79       88
9  S10    61       69       57
math size: (10,)
english size: (10,)
science size: (10,)


### Q37. Using NumPy on the arrays from Q36, compute the mean score of each subject (math, english, science) and print them.

In [113]:
# answer here
mean_math = math.mean()
mean_english = english.mean()
mean_science = science.mean()
print('mean score of math:',mean_math)
print('mean score of english:',mean_english)
print('mean score of science:',mean_science)

mean score of math: 70.3
mean score of english: 69.5
mean score of science: 70.1


### Q38. Using NumPy, compute each student’s **total score** (math + english + science) and print the `id` of the student with the highest total.

In [114]:
# answer here
# df['total'] = df[['math', 'english', 'science']].sum(axis=1)
# print(df[['id', 'total']])

ids = df['id'].to_numpy()
total = math + english + science
maxmarks = np.argmax(total)
print(ids[maxmarks])


S03


### Q39. Using NumPy, standardize the `math` scores to **z-scores**: `(x - mean) / std` and print the first 5 standardized values.

In [115]:
# answer here
std = np.std(math)
z_score = (math - mean_math)/(std)
print(np.round(z_score[:5],2))

[ 0.53 -0.98  1.22 -1.74  1.49]


In [116]:
# this is how you can approach question number 39
# dont fear about std(standard deviation , just google it and you understand its simple, else you can connect for doubts)


import pandas as pd
import numpy as np

# Load the dataset
df = pd.read_csv("students_scores.csv")

# Extract math column as NumPy array
math_scores = df["math"].values

# Compute z-scores
z_scores = (math_scores - np.mean(math_scores)) / np.std(math_scores)

# Print first 5 standardized values
print(z_scores[:5])


[ 0.53032869 -0.98489614  1.21906724 -1.74250855  1.49456267]


### Q40. Using NumPy logical operations, count how many students scored **≥ 70 in all three subjects** and print that count.

In [117]:
# answer here
ans = np.sum((math >= 70) & (english >= 70) & (science >= 70))
print(ans)

3
